# Generated by Django 4.2.5 on 2023-09-22 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='app_product.lesson', verbose_name='Lessons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Customers'),
        ),
    ]
